### ISSUE TITLE
awesome_bot issues

### ISSUE THREAD

**Issue by stevestock** [monostable/awesome-electronics#27]
[awesome_bot](https://github.com/dkhamsing/awesome_bot) output below.  I can make a PR if you're interested.  You also may want to set up [Travis CI](https://travis-ci.org) to check this automatically like [several](https://github.com/vinta/awesome-python/blob/master/.travis.yml) [other](https://github.com/vsouza/awesome-ios/blob/master/.travis.yml) [awesome](https://github.com/ziadoz/awesome-php/blob/master/.travis.yml) [lists](https://github.com/jaywcjlove/awesome-mac/blob/master/.travis.yml).

```sh
$ awesome_bot readme.md
...
Issues :-(
> Links 
  01. [L043] 301 http://www.linear.com/designtools/software/#LTspice  → http://www.analog.com/en/design-center/design-tools-and-calculators.html?domain=www.linear.com 
  02. [L044] 503 http://ngspice.sourceforge.net/  
  03. [L047] 503 http://qucs.sourceforge.net/  
  04. [L057] 301 http://circuitpeople.com/  → https://circuitpeople.com/ 
  05. [L066]  https://cadsoft.io/ SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired) 
  06. [L067] 301 http://www.rs-online.com/designspark/electronics/eng/page/designspark-pcb-home-page  → https://www.rs-online.com/designspark/pcb-software 
  07. [L068] 302 http://circuitmaker.com/  → https://circuitmaker.com/ 
  08. [L089] 301 http://pcbshopper.com  → https://pcbshopper.com/ 
  09. [L092] 302 http://dirtypcbs.com  → http://dirtypcbs.com/store 
  10. [L096] 301 https://findchips.com  → https://www.findchips.com/ 
  11. [L104]  https://1clickBOM.com SSL_connect returned=1 errno=0 state=error: certificate verify failed (error number 1) 
  12. [L111] 301 https://snapeda.com  → https://www.snapeda.com/ 
  13. [L114] 301 https://sparkfun.com/  → http://www.sparkfun.com/ 
  14. [L127] 301 https://www.eevblog.com/forum  → http://www.eevblog.com/forum/ 
  15. [L128] 301 https://reddit.com/r/electronics  → https://www.reddit.com/r/electronics 
  16. [L128] 301 https://reddit.com/r/ECE  → https://www.reddit.com/r/ECE 
  17. [L131] 301 https://reddit.com/r/askelectronics  → https://www.reddit.com/r/askelectronics 
  18. [L137] 301 http://www.theamphour.com/  → http://theamphour.com/ 
  19. [L138] 301 http://embedded.fm/  → https://www.embedded.fm/ 
  20. [L161] 301 http://mightyohm.com/blog/2011/04/soldering-is-easy-comic-book/  → https://mightyohm.com/blog/2011/04/soldering-is-easy-comic-book/ 
  21. [L162] 301 http://www.instructables.com/id/Uses-of-Different-Soldering-Iron-Tips/?ALLSTEPS  → http://www.instructables.com/id/Uses-of-Different-Soldering-Iron-Tips/ 
  22. [L165] 301 http://www.allaboutcircuits.com/textbook/  → https://www.allaboutcircuits.com/textbook/ 
> Dupes 
  1. [L61] http://kicad-pcb.org/
```

**Comment by kasbah** [comment]
I guess so, I don't think these are huge issues. So what if the URLs re-direct?  The dupe KiCad link is intentional. 

Would be nice to check for 404s I guess. But those can just be temporary too.

**Comment by stevestock** [comment]
I don’t think they are huge issues either, just minor improvements.
Most redirects have a small impact to load time. Some, like link 01 (
linear.com to analog.com) could eventually be removed. Awesome_bot can be
configured to ignore dupes.

**Comment by kasbah** [comment]
Sure, feel free to change these but I don't think I want CI complaining
about people adding links which re-direct. Detecting dupes on PRs could be
handy but only if it can be configured to ignore specific instances like
the one we already have.

**Comment by stevestock** [comment]
Doesn’t look like it can ignore specific instances. I’ll make a PR tonight
for the issues it found. No worries if you don’t want to add an automatic
CI check, up to you. Just a suggestion.
