### ISSUE TITLE
Boldport Club

### ISSUE THREAD

**Issue by stevestock** [monostable/awesome-electronics#28]
Would like to see [Boldport Club](https://www.boldport.club) on the list, but not sure what category is appropriate.  Any ideas?

**Comment by kasbah** [comment]
We could maybe add a section "Subscription Kit Services" and add the  [AdaBox](https://www.adafruit.com/adabox) as well.

**Comment by stevestock** [comment]
I love that idea. Let me know if you want me to make the PR, or you got it

**Comment by kasbah** [comment]
Go for it.
